#!/usr/bin/env bash
# open-refvalues-pr.sh <cloud> <boot_format> <version> <env> [owner]
# Commit the generated reference-values json and open a PR into dev. Needs GH_TOKEN + gh.
#   canonical (owner omitted): commits <env>.json, branch/PR has no owner suffix
#   custom    (owner given):   commits <env>/<owner>.json, branch/PR includes owner
set -euo pipefail
cd "$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"   # repo root
CLOUD="${1:?}"; BOOT_FORMAT="${2:?}"; VERSION="${3:?}"; ENV="${4:?}"
OWNER="$(printf '%s' "${5:-}" | sed 's/^0[xX]//' | tr 'A-Z' 'a-z')"

if [ -n "$OWNER" ]; then
  REF="verifier/reference-values/${CLOUD}/${BOOT_FORMAT}/${VERSION}/${ENV}/${OWNER}.json"
  BR="refvalues/${CLOUD}-${BOOT_FORMAT}-${VERSION}-${ENV}-${OWNER}"
  TITLE="chore(verifier): reference values ${CLOUD} ${BOOT_FORMAT} ${VERSION} ${ENV} ${OWNER}"
  BODY="Auto-generated by build-cvm (custom mode) for ${CLOUD}/${BOOT_FORMAT} ${VERSION}/${ENV}, owner ${OWNER}. Registered on AS as policy \`0g-tapp-${CLOUD}-${BOOT_FORMAT}-${VERSION}-${ENV}-${OWNER}_cpu\`."
else
  REF="verifier/reference-values/${CLOUD}/${BOOT_FORMAT}/${VERSION}/${ENV}.json"
  BR="refvalues/${CLOUD}-${BOOT_FORMAT}-${VERSION}-${ENV}"
  TITLE="chore(verifier): reference values ${CLOUD} ${BOOT_FORMAT} ${VERSION} ${ENV}"
  BODY="Auto-generated by build-cvm (canonical mode) for ${CLOUD}/${BOOT_FORMAT} ${VERSION}/${ENV}. Registered on AS as policy \`0g-tapp-${CLOUD}-${BOOT_FORMAT}-${VERSION}-${ENV}_cpu\`."
fi

[ -f "$REF" ] || { echo "no reference file to commit: $REF" >&2; exit 1; }

git config user.name  "${GIT_AUTHOR_NAME:-cvm-ci}"
git config user.email "${GIT_AUTHOR_EMAIL:-cvm-ci@0g.ai}"
git fetch origin dev
git checkout -B "$BR" origin/dev
git add "$REF"
git commit -m "$TITLE" || { echo "no change to commit"; exit 0; }
git push -u origin "$BR" --force-with-lease
# `gh pr create` fails for two very different reasons and they must not be treated alike:
# the PR already exists (benign — a rebuild of the same identity), or the credential is
# broken (expired RELEASE_PAT → "HTTP 401: Bad credentials"). Swallowing both made a dead
# PAT look like a green build with no PR: the branch was pushed, the reference values were
# registered on the AS, and nobody noticed the PR was missing. Only the benign case passes.
if OUT="$(gh pr create --base dev --head "$BR" --title "$TITLE" --body "$BODY" 2>&1)"; then
  printf '%s\n' "$OUT"
else
  printf '%s\n' "$OUT" >&2
  case "$OUT" in
    *"already exists"*) echo "(PR already exists for $BR — nothing to do)" ;;
    *) echo "error: gh pr create failed for $BR (branch IS pushed — check GH_TOKEN/RELEASE_PAT, then open the PR by hand)" >&2
       exit 1 ;;
  esac
fi
