#!/usr/bin/env bash
# open-refvalues-pr.sh <cloud> <boot_format> <version> <env> [owner]
# Commit the generated reference-values json and open a PR into dev. Needs GH_TOKEN + gh.
#   canonical (owner omitted): commits <env>.json, branch/PR has no owner suffix
#   custom    (owner given):   commits <env>/<owner>.json, branch/PR includes owner
set -euo pipefail
cd "$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"   # repo root
CLOUD="${1:?}"; BOOT_FORMAT="${2:?}"; VERSION="${3:?}"; ENV="${4:?}"
OWNER="$(printf '%s' "${5:-}" | sed 's/^0[xX]//' | tr 'A-Z' 'a-z')"

if [ -n "$OWNER" ]; then
  REF="verifier/reference-values/${CLOUD}/${BOOT_FORMAT}/${VERSION}/${ENV}/${OWNER}.json"
  BR="refvalues/${CLOUD}-${BOOT_FORMAT}-${VERSION}-${ENV}-${OWNER}"
  TITLE="chore(verifier): reference values ${CLOUD} ${BOOT_FORMAT} ${VERSION} ${ENV} ${OWNER}"
  BODY="Auto-generated by build-cvm (custom mode) for ${CLOUD}/${BOOT_FORMAT} ${VERSION}/${ENV}, owner ${OWNER}. Registered on AS as policy \`0g-tapp-${CLOUD}-${BOOT_FORMAT}-${VERSION}-${ENV}-${OWNER}_cpu\`."
else
  REF="verifier/reference-values/${CLOUD}/${BOOT_FORMAT}/${VERSION}/${ENV}.json"
  BR="refvalues/${CLOUD}-${BOOT_FORMAT}-${VERSION}-${ENV}"
  TITLE="chore(verifier): reference values ${CLOUD} ${BOOT_FORMAT} ${VERSION} ${ENV}"
  BODY="Auto-generated by build-cvm (canonical mode) for ${CLOUD}/${BOOT_FORMAT} ${VERSION}/${ENV}. Registered on AS as policy \`0g-tapp-${CLOUD}-${BOOT_FORMAT}-${VERSION}-${ENV}_cpu\`."
fi

[ -f "$REF" ] || { echo "no reference file to commit: $REF" >&2; exit 1; }

git config user.name  "${GIT_AUTHOR_NAME:-cvm-ci}"
git config user.email "${GIT_AUTHOR_EMAIL:-cvm-ci@0g.ai}"
git fetch origin dev
git checkout -B "$BR" origin/dev
git add "$REF"
git commit -m "$TITLE" || { echo "no change to commit"; exit 0; }
git push -u origin "$BR" --force-with-lease
gh pr create --base dev --head "$BR" --title "$TITLE" --body "$BODY" \
  || echo "(PR may already exist for $BR)"
