//! Redirect named volumes into the app's encrypted volume.
//!
//! Nearly every compose file in the wild stores its state in named volumes
//! (`pgdata:/var/lib/postgresql/data`), which docker would put in its shared
//! data-root — outside the app's encrypted volume, in plaintext. Rather than
//! asking every author to learn a `./data` convention, the platform generates a
//! `docker-compose.override.yml` next to the user's file that redefines each
//! named volume as a bind into `<app_dir>/data/volumes/<name>`. Compose merges
//! override files automatically, so the user's compose runs verbatim and its
//! measured hash is untouched — the override is a deterministic product of the
//! platform code, which the image measurement already vouches for.
//!
//! Only plainly-declared volumes are redirected. A volume the user configured
//! explicitly (`external: true`, a driver, driver_opts…) is a choice this must
//! not silently rewrite; those are left alone and the lint points at them.

use std::collections::BTreeMap;

/// The volume names in `compose` that can be redirected: declared at top level
/// with no configuration of their own. Sorted, deduplicated.
pub fn redirectable_volumes(compose_content: &str) -> Vec<String> {
    let doc: serde_yaml::Value = match serde_yaml::from_str(compose_content) {
        Ok(v) => v,
        Err(_) => return Vec::new(),
    };
    let mut out = BTreeMap::new();
    if let Some(vols) = doc.get("volumes").and_then(|v| v.as_mapping()) {
        for (name, spec) in vols {
            let Some(name) = name.as_str() else { continue };
            let plain = match spec {
                serde_yaml::Value::Null => true,
                serde_yaml::Value::Mapping(m) => m.is_empty(),
                _ => false,
            };
            if plain {
                out.insert(name.to_string(), ());
            }
        }
    }
    out.into_keys().collect()
}

/// The override file content for `app_dir`, or None when there is nothing to
/// redirect. Volume names come from compose's own grammar (`[a-zA-Z0-9._-]+`),
/// and the generated YAML quotes them anyway.
pub fn generate(compose_content: &str, app_dir: &std::path::Path) -> Option<String> {
    let names = redirectable_volumes(compose_content);
    if names.is_empty() {
        return None;
    }
    let mut out = String::from(
        "# GENERATED by tapp-server — do not edit.\n\
         # Named volumes are redirected into the app's encrypted data volume, so\n\
         # their contents are encrypted at rest and survive reboots. See volume.rs.\n\
         volumes:\n",
    );
    for name in &names {
        let device = app_dir.join("data/volumes").join(name);
        out.push_str(&format!(
            "  \"{name}\":\n    driver: local\n    driver_opts:\n      type: none\n      o: bind\n      device: \"{}\"\n",
            device.display()
        ));
    }
    Some(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    const APP: &str = "/var/lib/tapp/apps/myapp";

    #[test]
    fn a_plain_named_volume_is_redirected_into_the_encrypted_volume() {
        let compose = "services:\n  db:\n    image: postgres\n    volumes:\n      - pgdata:/var/lib/postgresql/data\nvolumes:\n  pgdata:\n";
        let ovr = generate(compose, Path::new(APP)).expect("must redirect");
        assert!(ovr.contains("\"pgdata\":"));
        assert!(ovr.contains("device: \"/var/lib/tapp/apps/myapp/data/volumes/pgdata\""));
        // The override itself must be valid YAML with the same volume name.
        let parsed: serde_yaml::Value = serde_yaml::from_str(&ovr).unwrap();
        assert!(parsed.get("volumes").unwrap().get("pgdata").is_some());
    }

    #[test]
    fn configured_volumes_are_a_user_choice_and_left_alone() {
        // external: the user points at a volume that already exists elsewhere;
        // driver_opts: the user configured storage themselves. Rewriting either
        // would silently change what they asked for.
        let compose = "volumes:\n  ext:\n    external: true\n  custom:\n    driver_opts:\n      type: tmpfs\n  plain:\n";
        assert_eq!(redirectable_volumes(compose), vec!["plain"]);
    }

    #[test]
    fn no_named_volumes_means_no_override_file() {
        assert!(generate("services:\n  a:\n    image: nginx\n", Path::new(APP)).is_none());
        assert!(generate(": not yaml ::", Path::new(APP)).is_none());
    }

    #[test]
    fn empty_mapping_counts_as_plain() {
        let compose = "volumes:\n  data: {}\n";
        assert_eq!(redirectable_volumes(compose), vec!["data"]);
    }
}
