#!/usr/bin/env bash
# open-refvalues-pr.sh <cloud> <version> <env> <owner>
# Commit the generated reference-values json and open a PR into dev. Needs GH_TOKEN + gh.
set -euo pipefail
cd "$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"   # repo root
CLOUD="${1:?}"; VERSION="${2:?}"; ENV="${3:?}"; OWNER="$(printf '%s' "${4:?}" | tr 'A-Z' 'a-z')"
REF="verifier/reference-values/${CLOUD}/${VERSION}/${ENV}/${OWNER}.json"
[ -f "$REF" ] || { echo "no reference file to commit: $REF" >&2; exit 1; }

BR="refvalues/${CLOUD}-${VERSION}-${ENV}-${OWNER}"
git config user.name  "${GIT_AUTHOR_NAME:-cvm-ci}"
git config user.email "${GIT_AUTHOR_EMAIL:-cvm-ci@0g.ai}"
git fetch origin dev
git checkout -B "$BR" origin/dev
git add "$REF"
git commit -m "chore(verifier): reference values for ${CLOUD}/${VERSION}/${ENV}/${OWNER}" || { echo "no change to commit"; exit 0; }
git push -u origin "$BR" --force-with-lease
gh pr create --base dev --head "$BR" \
  --title "chore(verifier): reference values ${CLOUD} ${VERSION} ${ENV} ${OWNER}" \
  --body "Auto-generated by build-cvm for the ${CLOUD} image \`og-tdx${ENV:+-}${ENV/prod/}\` ${VERSION}, owner ${OWNER}. Registered on AS as policy \`0g-tapp-${CLOUD}-${VERSION}-${ENV}-${OWNER}_cpu\`." \
  || echo "(PR may already exist for $BR)"
